/**
 * Auto Generated and Deployed by the Declarative Lookup Rollup Summaries Tool package (dlrs)
 **/
@IsTest
private class dlrs_Case_Equip_JunctionTest
{
  /*  @IsTest
    private static void testTrigger()
    {
        // Force the dlrs_Case_Equip_JunctionTrigger to be invoked, fails the test if org config or other Apex code prevents this.
        dlrs.RollupService.testHandler(new Case_Equip_Junction__c());
    }*/
}