/* DEPRECATED - SAFE TO DELETE */
global class VendavoAgreementUpdateBatchable {
    
    /*global Database.QueryLocator start(Database.BatchableContext BC) {
        String query = 'SELECT Id, VendavoId__c, Owner_Vendavo_Id__c, Owner_Vendavo_Uid__c, Vendavo__VVersionNumber__c FROM Vendavo__Deal__c WHERE LastModifiedDate >= TODAY AND Vendavo__VVersionNumber__c != NULL';
        return Database.getQueryLocator(query);
    }
    
    global void execute(Database.BatchableContext BC, List<Vendavo__Deal__c> scope) {
        //String token = VendavoUtils.getAuthToken();
        //VendavoAgreementsSync.createDealConnections(scope, token);
    }   
    
    global void finish(Database.BatchableContext BC) {
        
    }*/
    
}